update to python version for conda env
update to python version as I got the following error:

ERROR: Package 'neurodocker' requires a different Python: 3.8.20 not in '>=3.9'